---
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  ignore_errors: yes
  tasks:
    - name: New tasks
      packages: 
        name: httpd
        state: installed

    - name: Add user
      user: 
        name: bob
        state: present

    - name: add Group
      group:
        name: managers
        state: present

